version: '3.8'
services:
  bill_users_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    volumes:
      - .:/app
    depends_on:
      - bill_users_api_db
    networks:
      - bill-network
  bill_users_api_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: bill_users_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33070:3306
    networks:
      - bill-network
networks:
  bill-network:
    external: true
